name: Deploy ./kwaa.dev to Deno Deploy

on:
  push:
    branch:
      - main
    paths:
      - posts/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: kwaa-bk
          entrypoint: main.ts